[package]

name = "wire"
version = "0.0.1"
authors = ["TyOverby <ty@pre-alpha.com>"]

repository = "https://github.com/TyOverby/wire"
documentation = "http://tyoverby.com/wire/wire/index.html"
keywords = ["tcp", "serialization", "encode", "network"]
description = "An abstraction over TCP and struct serialization"

[dependencies.bincode]
git = "https://github.com/TyOverby/bincode.git"

[dependencies.bchannel]
git = "https://github.com/TyOverby/bchannel.git"
